kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: bootcamp
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 30080  # For frontend
      hostPort: 30080
      protocol: TCP
    - containerPort: 30081  # For backend
      hostPort: 30081
      protocol: TCP
  - role: worker
  - role: worker
  - role: worker
