apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: task-app
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: "taskDB"

  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"

  NODE_ENV: "development"
  LOG_LEVEL: "info"
  API_PORT: "3000"

  # Frontend configuration
  REACT_APP_API_URL: "http://localhost:30081/api"
