apiVersion: v1
kind: Secret
metadata:
  name:  app-secrets
  namespace: task-app
type: Opaqie
stringData: # Using stringData - Kubernetes will base64 encode for us
  DB_USER: "postgres"
  DB_PASSWORD: "postgres123"
  REDIS_PASSWORD: "redis123"
  JWT_SECRET: "your-secret-jwt-key-change-in-production-please"

