apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: task-app

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-metadata-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd-metadata-reader-binding
subjects:
  - kind: ServiceAccount
    name: fluentd
    namespace: task-app
roleRef:
  kind: ClusterRole
  name: fluentd-metadata-reader
  apiGroup: rbac.authorization.k8s.io
